#!/usr/bin/env python3
"""Generate the Astro Lab's dependency-free static HTML pages."""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "site.json"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def load_data() -> dict:
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def href(output_path: str, target: str) -> str:
    if urlparse(target).scheme or target.startswith(("mailto:", "#")):
        return target
    start = (ROOT / output_path).parent
    return os.path.relpath(ROOT / target, start=start).replace(os.sep, "/")


def public_url(output_path: str) -> str:
    relative = output_path.removesuffix("index.html")
    return f"https://activities.tjhsst.edu/astro/{relative}"


def projects_for_year(data: dict, year_slug: str) -> list[dict]:
    return [project for project in data["projects"] if project["year"] == year_slug]


def year_definition(data: dict, year_slug: str) -> dict:
    return next(year for year in data["years"] if year["slug"] == year_slug)


def noun(count: int, singular: str, plural: str | None = None) -> str:
    return singular if count == 1 else (plural or f"{singular}s")


def natural_list(items: list[str]) -> str:
    if len(items) < 2:
        return "".join(items)
    if len(items) == 2:
        return " and ".join(items)
    return f"{', '.join(items[:-1])}, and {items[-1]}"


def nav_link(output_path: str, target: str, label: str, active: bool) -> str:
    marker = ' aria-current="page"' if active else ""
    return f'<a href="{esc(href(output_path, target))}"{marker}>{esc(label)}</a>'


def family_strip(site: dict) -> str:
    items: list[str] = []
    for item in site["family_links"]:
        label = esc(item["label"])
        if item.get("current"):
            content = f'<span class="family-current" aria-current="page">{label}</span>'
        elif item.get("url"):
            content = f'<a href="{esc(item["url"])}">{label}</a>'
        else:
            content = f'<span class="family-placeholder">{label}</span>'
        items.append(f"<li>{content}</li>")
    return f"""<nav class="family-strip" aria-label="Astro at TJ">
    <div class="family-inner">
      <span class="family-label">Astro at TJ</span>
      <ul>{''.join(items)}</ul>
    </div>
  </nav>"""


def layout(
    *,
    output_path: str,
    title: str,
    description: str,
    active: str,
    content: str,
    site: dict,
) -> str:
    full_title = site["full_name"]
    page_title = full_title if title == full_title else f"{title} | {site['name']}"
    nav = "".join(
        f"<li>{nav_link(output_path, item['path'], item['label'], active == item['key'])}</li>"
        for item in site["primary_nav"]
    )
    css = href(output_path, "assets/site.css")
    js = href(output_path, "assets/countdown.js")
    home = href(output_path, "index.html")
    email = esc(site["contact_email"])
    if output_path == "index.html":
        lab_identity = '<span class="site-name" aria-current="page">Astronomy &amp; Astrophysics Research</span>'
    else:
        lab_identity = f'<a class="site-name" href="{esc(home)}">Astronomy &amp; Astrophysics Research</a>'
    return f"""<!doctype html>
<!-- Generated by scripts/build_site.py; edit data/site.json or the generator. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(page_title)}</title>
  <meta name="description" content="{esc(description)}">
  <link rel="canonical" href="{esc(public_url(output_path))}">
  <link rel="stylesheet" href="{esc(css)}">
  <script src="{esc(js)}" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to main content</a>
  <header class="site-header">
    <div class="header-inner">
      <div class="site-mark">
        <a class="site-mark-kicker" href="{esc(site['school_url'])}">TJHSST</a>
        <span class="site-mark-separator" aria-hidden="true">/</span>
        {lab_identity}
      </div>
      <nav aria-label="Primary navigation">
        <ul>{nav}</ul>
      </nav>
    </div>
  </header>
  {family_strip(site)}
  <main id="main">{content}</main>
  <footer class="site-footer">
    <div>
      <p><strong>{esc(full_title)}</strong><br>Thomas Jefferson High School for Science and Technology</p>
      <p><a href="mailto:{email}">Contact the lab director</a></p>
    </div>
    <p class="footer-note">Public research records and retained student work from the TJHSST Astronomy &amp; Astrophysics Research Lab.</p>
  </footer>
</body>
</html>
"""


def countdown(site: dict, featured: bool = False) -> str:
    classes = "tjstar-marker deadline-card" if featured else "tjstar-marker"
    return f"""<div class="{classes}">
  <p class="rail-label">Next tjSTAR</p>
  <time datetime="{esc(site['tjstar_datetime'])}">{esc(site['tjstar_display'])}</time>
  <span class="countdown" data-tjstar-countdown="{esc(site['tjstar_datetime'])}" aria-hidden="true"></span>
  <a href="{esc(site['tjstar_url'])}">Astronomy presentations</a>
</div>"""


def project_card(project: dict, output_path: str, heading_level: int = 3) -> str:
    target = f"{project['year']}/{project['slug']}/index.html"
    available = [
        f'<a href="{esc(href(output_path, item["path"]))}">{esc(item["label"])}</a>'
        for item in project["artifacts"]
    ]
    available.append(f'<a href="{esc(project["tjstar_url"])}">tjSTAR record</a>')
    available_links = ' <span aria-hidden="true">·</span> '.join(available)
    return f"""<article class="project-card">
  <p class="project-topic">{esc(project['topic'])}</p>
  <h{heading_level}><a href="{esc(href(output_path, target))}">{esc(project['title'])}</a></h{heading_level}>
  <p>{esc(project['summary'])}</p>
  <p class="project-availability"><span>Available:</span> {available_links}</p>
</article>"""


def home_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    latest_year = site["latest_year"]
    year = year_definition(data, latest_year)
    projects = projects_for_year(data, latest_year)
    output = "index.html"
    feature_indexes = sorted({0, len(projects) // 2, len(projects) - 1}) if projects else []
    featured = "\n".join(project_card(projects[index], output) for index in feature_indexes)
    archive_link = href(output, f"{latest_year}/index.html")
    research_link = href(output, "research/index.html")
    content = f"""
<div class="home-shell">
  <div class="home-grid">
    <section class="home-intro" aria-labelledby="page-title">
      <p class="eyebrow">Thomas Jefferson High School for Science and Technology</p>
      <h1 id="page-title">{esc(site['full_name'])}</h1>
      <p class="lede">TJHSST's senior research laboratory for sustained work in astronomy, astrophysics, astronomical data analysis, instrumentation, and computational modeling.</p>
      <div class="quick-actions" aria-label="Featured actions">
        <a class="button primary" href="{esc(href(output, 'about/index.html'))}">How the lab works</a>
      </div>
    </section>
    <aside class="home-sidebar" aria-label="Research deadlines and archive">
      {countdown(site, featured=True)}
      <div class="research-rail" aria-labelledby="research-now-title">
        <p class="rail-label">Research archive</p>
        <h2 id="research-now-title">Latest work</h2>
        <a class="year-link" href="{esc(archive_link)}">
          <span>{esc(year['label'])}</span>
          <small>{len(projects)} {noun(len(projects), 'project record')}</small>
        </a>
        <a class="rail-link" href="{esc(research_link)}">Browse research by year</a>
      </div>
    </aside>
  </div>

  <section class="home-section" aria-labelledby="featured-title">
    <div class="section-heading">
      <div>
        <p class="eyebrow">Recent research</p>
        <h2 id="featured-title">Selected {esc(year['label'])} projects</h2>
      </div>
      <a class="text-link" href="{esc(archive_link)}">View all {len(projects)} projects</a>
    </div>
    <div class="project-grid">{featured}</div>
  </section>

</div>"""
    return output, site["full_name"], "TJHSST's senior research laboratory for astronomy and astrophysics.", content


def research_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    output = "research/index.html"
    latest_slug = site["latest_year"]
    latest_year = year_definition(data, latest_slug)
    latest_projects = projects_for_year(data, latest_slug)
    latest_topics = list(dict.fromkeys(project["topic"].lower() for project in latest_projects))
    earlier_years = [year for year in reversed(data["years"]) if year["slug"] != latest_slug]
    archive_links = "\n".join(
        f'<a class="year-link compact-year-link" href="{esc(href(output, f"{year["slug"]}/index.html"))}"><span>{esc(year["label"])}</span><small>{len(projects_for_year(data, year["slug"]))} {noun(len(projects_for_year(data, year["slug"])), "project record")}</small></a>'
        for year in earlier_years
    )
    earlier_archives = f'<div class="year-list" aria-label="Earlier research years">{archive_links}</div>' if archive_links else ""
    content = f"""
<div class="page-shell">
  <header class="page-heading">
    <h1>Research archive</h1>
    <p class="lede">Browse project records by year. Each record summarizes the question, method, and result and links to retained papers and posters.</p>
  </header>
  <div class="research-index-grid">
    <section class="year-feature" aria-labelledby="year-title">
      <p class="rail-label">Latest available year</p>
      <h2 id="year-title">{esc(latest_year['label'])} research</h2>
      <p>{len(latest_projects)} {noun(len(latest_projects), 'project')} spanning {esc(natural_list(latest_topics))}.</p>
      <a class="button primary" href="{esc(href(output, f'{latest_slug}/index.html'))}">Open the {esc(latest_year['label'])} archive</a>
{earlier_archives}
    </section>
    <aside class="research-rail research-index-rail" aria-label="Research events">
      {countdown(site)}
    </aside>
  </div>
</div>"""
    return output, "Research", "Browse annual research records from the TJHSST Astronomy & Astrophysics Research Lab.", content


def about_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    classes_url = next(item["url"] for item in site["family_links"] if item["label"] == "Classes")
    output = "about/index.html"
    content = f"""
<div class="page-shell article-shell">
  <header class="page-heading">
    <p class="eyebrow">About the lab</p>
    <h1>Senior research in Astro Lab</h1>
    <p class="lede">Students complete a year-long astronomy or astrophysics research project and present the resulting work.</p>
  </header>
  <section class="content-section" aria-labelledby="practice-title">
    <h2 id="practice-title">Research process</h2>
    <div class="practice-grid">
      <article><h3>Develop</h3><p>Read technical literature, identify a tractable question, and design a research plan with appropriate evidence.</p></article>
      <article><h3>Investigate</h3><p>Use observations, archives, computation, simulation, or instrumentation while recording choices and uncertainty.</p></article>
      <article><h3>Communicate</h3><p>Explain methods and conclusions through research writing, posters, talks, and critique from a scientific audience.</p></article>
    </div>
  </section>
  <section class="content-section prospective-section" aria-labelledby="prospective-title">
    <p class="eyebrow">For prospective students</p>
    <h2 id="prospective-title">Preparing for senior research</h2>
    <p>Junior students interested in senior research in Astro Lab are encouraged to build their astronomy background through TJ's Advanced Astronomy electives. The electives support later research work with shared scientific context, quantitative methods, and astronomical problem solving.</p>
    <p class="quiet-link"><a href="{esc(classes_url)}">View the current Classes site</a></p>
  </section>
  <section class="content-section split-section" aria-labelledby="modes-title">
    <div>
      <p class="eyebrow">Research modes</p>
      <h2 id="modes-title">Methods used in the lab</h2>
    </div>
    <ul class="plain-list">
      <li>Observational astronomy and calibrated measurement</li>
      <li>Public survey catalogs, images, spectra, and time series</li>
      <li>Numerical models and computational astrophysics</li>
      <li>Instrumentation, automation, and data-quality methods</li>
    </ul>
  </section>
  <section class="content-section callout-section" aria-labelledby="records-title">
    <div>
      <p class="eyebrow">Public record</p>
      <h2 id="records-title">Project records</h2>
    </div>
    <a class="button primary" href="{esc(href(output, 'research/index.html'))}">Browse research</a>
  </section>
</div>"""
    return output, "About the Lab", "How students conduct astronomy and astrophysics research at TJHSST.", content


def contact_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    output = "contact/index.html"
    email = esc(site["contact_email"])
    profile_links = "\n".join(
        f'''<a class="profile-link" href="{esc(item['url'])}">
  <span>{esc(item['label'])}</span><small>{esc(item['detail'])}</small>
</a>'''
        for item in site["director_profiles"]
    )
    content = f"""
<div class="page-shell article-shell">
  <header class="page-heading">
    <h1>Contact</h1>
    <p class="lede">Contact the lab director about senior research, student projects, or research collaboration.</p>
  </header>
  <div class="contact-layout">
    <section class="contact-card director-card" aria-labelledby="director-title">
      <p class="rail-label">Lab director</p>
      <h2 id="director-title">{esc(site['director_name'])}</h2>
      <p class="director-role">Director, Astronomy &amp; Astrophysics Research</p>
      <p>Thomas Jefferson High School for Science and Technology</p>
      <a class="button primary" href="mailto:{email}">Email the lab director</a>
    </section>
    <section class="profile-panel" aria-labelledby="profiles-title">
      <p class="rail-label">Professional record</p>
      <h2 id="profiles-title">Professional profiles</h2>
      <div class="profile-links">{profile_links}</div>
    </section>
  </div>
</div>"""
    return output, "Contact", "Contact the TJHSST Astronomy & Astrophysics Research Lab.", content


def institution_card(item: dict) -> str:
    return f'''<a class="institution-card" href="{esc(item['url'])}">
  <span class="institution-mark" aria-hidden="true">{esc(item['short'])}</span>
  <span class="institution-copy"><small>{esc(item['kind'])}</small><strong>{esc(item['name'])}</strong></span>
</a>'''


def partners_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    output = "partners/index.html"
    email = esc(site["contact_email"])
    partners = "\n".join(institution_card(item) for item in data["partners"])
    supporters = "\n".join(institution_card(item) for item in data["supporters"])
    practicum = data["research_practicum"]
    content = f"""
<div class="page-shell article-shell wide-article-shell">
  <header class="page-heading">
    <h1>Partners</h1>
    <p class="lede">Astro Lab students have worked with researchers and received support from the organizations and universities listed below.</p>
  </header>
  <section class="partner-section" aria-labelledby="research-partners-title">
    <p class="rail-label">Research partners</p>
    <h2 id="research-partners-title">Organizations and universities</h2>
    <div class="institution-grid">{partners}</div>
  </section>
  <div class="partner-support-grid">
    <section class="partner-section supporter-section" aria-labelledby="supporters-title">
      <h2 id="supporters-title">Donor support</h2>
      <div class="institution-grid supporter-grid">{supporters}</div>
    </section>
    <section class="practicum-card" aria-labelledby="practicum-title">
      <div>
        <p class="rail-label">Off-site senior research</p>
        <h2 id="practicum-title">{esc(practicum['name'])}</h2>
        <p>{esc(practicum['description'])}</p>
      </div>
      <a class="button" href="{esc(practicum['url'])}">Visit Research Practicum</a>
    </section>
  </div>
  <section class="collaboration-card" aria-labelledby="collaborate-title">
    <div>
      <p class="eyebrow">For researchers and organizations</p>
      <h2 id="collaborate-title">Collaborate with Astro Lab</h2>
      <p>Researchers interested in mentoring a project, sharing resources, or proposing a collaboration can contact the lab director.</p>
    </div>
    <div class="card-actions">
      <a class="button primary" href="mailto:{email}">Email William D. Linch III</a>
      <a class="button" href="{esc(href(output, 'contact/index.html'))}">Contact information</a>
    </div>
  </section>
</div>"""
    return output, "Partners", "Research partners and supporters of the TJHSST Astronomy & Astrophysics Research Lab.", content


def labs_page(data: dict) -> tuple[str, str, str, str]:
    output = "labs/index.html"
    lab_data = data["tj_labs"]
    practicum = data["research_practicum"]
    cards: list[str] = []
    for item in lab_data["labs"]:
        link = ""
        if item.get("url"):
            link = f'  <a href="{esc(item["url"])}">{esc(item.get("link_label", "Visit lab site"))}</a>'
        cards.append(f'''<article class="lab-card">
  <h2>{esc(item['name'])}</h2>
{link}
</article>''')
    content = f"""
<div class="page-shell wide-article-shell">
  <header class="page-heading">
    <p class="eyebrow">TJ senior research</p>
    <h1>Other TJ research labs</h1>
    <p class="lede">TJHSST's senior research program includes eight other on-campus laboratories spanning science, engineering, and computing.</p>
    <p class="quiet-link"><a href="{esc(lab_data['overview_url'])}">View the official TJHSST Senior Research Labs overview</a></p>
  </header>
  <section aria-label="Other on-campus research labs">
    <div class="lab-grid">{''.join(cards)}</div>
  </section>
  <section class="practicum-card labs-practicum" aria-labelledby="labs-practicum-title">
    <div>
      <p class="rail-label">Off-site alternative</p>
      <h2 id="labs-practicum-title">{esc(practicum['name'])}</h2>
      <p>{esc(practicum['description'])}</p>
    </div>
    <a class="button primary" href="{esc(practicum['url'])}">Explore Research Practicum</a>
  </section>
</div>"""
    return output, "TJ Labs", "Explore TJHSST's other senior research labs and the Research Practicum alternative.", content


def artifact_link(item: dict, output_path: str) -> str:
    target = ROOT / item["path"]
    suffix = target.suffix.removeprefix(".").upper()
    size_mb = target.stat().st_size / (1024 * 1024)
    details = f"{suffix} · {size_mb:.1f} MB"
    return f'<a class="artifact-link" href="{esc(href(output_path, item["path"]))}"><span>{esc(item["label"])}</span><small>{esc(details)}</small></a>'


def year_page(data: dict, year: dict) -> tuple[str, str, str, str]:
    year_slug = year["slug"]
    projects = projects_for_year(data, year_slug)
    output = f"{year_slug}/index.html"
    cards = "\n".join(project_card(project, output, heading_level=2) for project in projects)
    content = f"""
<div class="page-shell">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="{esc(href(output, 'research/index.html'))}">Research</a><span aria-hidden="true">/</span><span>{esc(year['label'])}</span>
  </nav>
  <header class="page-heading archive-heading">
    <p class="eyebrow">Annual archive</p>
    <h1>{esc(year['label'])} projects</h1>
    <p class="lede">{len(projects)} concise {noun(len(projects), 'research record')}. Each page stands on its own as an account of the question, method, and result; retained papers, posters, and tjSTAR records provide the full artifacts.</p>
  </header>
  <div class="project-grid archive-grid">{cards}</div>
</div>"""
    return output, f"{year['label']} Projects", f"{len(projects)} {noun(len(projects), 'research project')} from the TJHSST Astronomy & Astrophysics Research Lab in {year['label']}.", content


def project_page(data: dict, project: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    year_slug = project["year"]
    year = year_definition(data, year_slug)
    output = f"{year_slug}/{project['slug']}/index.html"
    artifact_links = "\n".join(artifact_link(item, output) for item in project["artifacts"])
    tjstar = f'<a class="artifact-link" href="{esc(project["tjstar_url"])}"><span>tjSTAR record</span><small>Filtered presentation entry</small></a>'
    collaboration = ""
    if project.get("collaboration"):
        collaboration = f"""<section class="record-section" aria-labelledby="collaboration-title">
  <p class="record-label">Collaboration</p>
  <h2 id="collaboration-title">Project-specific support</h2>
  <p>{esc(project['collaboration'])}</p>
</section>"""
    credits = ""
    if site.get("show_project_credits") and project.get("credits") and project.get("external_collaboration"):
        credits = f"""<details class="project-credits">
  <summary>Project credits</summary>
  <p>Student researchers: {esc(', '.join(project['credits']))}</p>
</details>"""
    content = f"""
<div class="page-shell record-shell">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="{esc(href(output, 'research/index.html'))}">Research</a><span aria-hidden="true">/</span><a href="{esc(href(output, f'{year_slug}/index.html'))}">{esc(year['label'])}</a><span aria-hidden="true">/</span><span>{esc(project['topic'])}</span>
  </nav>
  <div class="record-layout">
    <article class="record-main">
      <header class="record-heading">
        <p class="eyebrow">{esc(project['topic'])}</p>
        <h1>{esc(project['title'])}</h1>
        <p class="lede">{esc(project['summary'])}</p>
      </header>
      <section class="record-section" aria-labelledby="question-title">
        <p class="record-label">Research question</p>
        <h2 id="question-title">What did the project ask?</h2>
        <p>{esc(project['question'])}</p>
      </section>
      <section class="record-section" aria-labelledby="significance-title">
        <p class="record-label">Significance</p>
        <h2 id="significance-title">Why does it matter?</h2>
        <p>{esc(project['significance'])}</p>
      </section>
      <section class="record-section" aria-labelledby="method-title">
        <p class="record-label">Method</p>
        <h2 id="method-title">What did the team do?</h2>
        <p>{esc(project['method'])}</p>
      </section>
      <section class="record-section result-section" aria-labelledby="result-title">
        <p class="record-label">Principal result</p>
        <h2 id="result-title">What did the evidence show?</h2>
        <p>{esc(project['result'])}</p>
      </section>
{collaboration}
    </article>
    <aside class="artifact-panel" aria-labelledby="artifacts-title">
      <p class="rail-label">Full work</p>
      <h2 id="artifacts-title">Project artifacts</h2>
      <div class="artifact-list">{artifact_links}{tjstar}</div>
      <p class="artifact-note">The HTML record is a concise public account. Papers and posters retain the project's full presentation and authorship.</p>
      <a class="back-link" href="{esc(href(output, f'{year_slug}/index.html'))}">Back to all {esc(year['label'])} projects</a>
{credits}
    </aside>
  </div>
</div>"""
    return output, project["title"], project["summary"], content


def render_all(data: dict) -> dict[str, str]:
    site = data["site"]
    specifications = [
        (*home_page(data), "home"),
        (*research_page(data), "research"),
        (*about_page(data), "about"),
        (*partners_page(data), "partners"),
        (*labs_page(data), "labs"),
        (*contact_page(data), "contact"),
    ]
    specifications.extend((*year_page(data, year), "research") for year in data["years"])
    specifications.extend((*project_page(data, project), "research") for project in data["projects"])
    rendered: dict[str, str] = {}
    for output_path, title, description, content, active in specifications:
        rendered[output_path] = layout(
            output_path=output_path,
            title=title,
            description=description,
            active=active,
            content=content,
            site=site,
        )
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated pages are missing or stale")
    args = parser.parse_args()
    rendered = render_all(load_data())
    stale: list[str] = []
    for relative, contents in rendered.items():
        destination = ROOT / relative
        if args.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != contents:
                stale.append(relative)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(contents, encoding="utf-8")
        print(f"generated {relative}")
    if stale:
        print("Generated pages are stale or missing:", file=sys.stderr)
        for relative in stale:
            print(f"  {relative}", file=sys.stderr)
        return 1
    if args.check:
        expected = set(rendered)
        for page in ROOT.rglob("*.html"):
            relative = page.relative_to(ROOT).as_posix()
            if "Generated by scripts/build_site.py" in page.read_text(encoding="utf-8") and relative not in expected:
                print(f"Orphan generated page: {relative}", file=sys.stderr)
                return 1
        print(f"All {len(rendered)} generated HTML pages are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
