#!/usr/bin/env python3
"""Generate the Astro Lab's dependency-free static HTML pages."""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "site.json"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def load_data() -> dict:
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def href(output_path: str, target: str) -> str:
    if urlparse(target).scheme or target.startswith(("mailto:", "#")):
        return target
    start = (ROOT / output_path).parent
    return os.path.relpath(ROOT / target, start=start).replace(os.sep, "/")


def public_url(output_path: str) -> str:
    relative = output_path.removesuffix("index.html")
    return f"https://activities.tjhsst.edu/astro/{relative}"


def projects_for_year(data: dict, year_slug: str) -> list[dict]:
    return [project for project in data["projects"] if project["year"] == year_slug]


def year_definition(data: dict, year_slug: str) -> dict:
    return next(year for year in data["years"] if year["slug"] == year_slug)


def noun(count: int, singular: str, plural: str | None = None) -> str:
    return singular if count == 1 else (plural or f"{singular}s")


def natural_list(items: list[str]) -> str:
    if len(items) < 2:
        return "".join(items)
    if len(items) == 2:
        return " and ".join(items)
    return f"{', '.join(items[:-1])}, and {items[-1]}"


def nav_link(output_path: str, target: str, label: str, active: bool) -> str:
    marker = ' aria-current="page"' if active else ""
    return f'<a href="{esc(href(output_path, target))}"{marker}>{esc(label)}</a>'


def layout(
    *,
    output_path: str,
    title: str,
    description: str,
    active: str,
    content: str,
    site: dict,
) -> str:
    full_title = site["full_name"]
    page_title = full_title if title == full_title else f"{title} | {site['name']}"
    nav = "".join(
        [
            f"<li>{nav_link(output_path, 'index.html', 'Home', active == 'home')}</li>",
            f"<li>{nav_link(output_path, 'research/index.html', 'Research', active == 'research')}</li>",
            f"<li>{nav_link(output_path, 'about/index.html', 'About', active == 'about')}</li>",
            f"<li>{nav_link(output_path, 'contact/index.html', 'Contact', active == 'contact')}</li>",
        ]
    )
    css = href(output_path, "assets/site.css")
    js = href(output_path, "assets/countdown.js")
    home = href(output_path, "index.html")
    email = esc(site["contact_email"])
    return f"""<!doctype html>
<!-- Generated by scripts/build_site.py; edit data/site.json or the generator. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(page_title)}</title>
  <meta name="description" content="{esc(description)}">
  <link rel="canonical" href="{esc(public_url(output_path))}">
  <link rel="stylesheet" href="{esc(css)}">
  <script src="{esc(js)}" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to main content</a>
  <header class="site-header">
    <div class="header-inner">
      <a class="site-mark" href="{esc(home)}">
        <span class="site-mark-kicker">TJHSST</span>
        <span>Astronomy &amp; Astrophysics Research</span>
      </a>
      <nav aria-label="Primary navigation">
        <ul>{nav}</ul>
      </nav>
    </div>
  </header>
  <main id="main">{content}</main>
  <footer class="site-footer">
    <div>
      <p><strong>{esc(full_title)}</strong><br>Thomas Jefferson High School for Science and Technology</p>
      <p><a href="mailto:{email}">Contact the lab director</a></p>
    </div>
    <p class="footer-note">Public research records and retained student work from the TJHSST Astronomy &amp; Astrophysics Research Lab.</p>
  </footer>
</body>
</html>
"""


def countdown(site: dict) -> str:
    return f"""<div class="tjstar-marker">
  <p class="rail-label">Next tjSTAR</p>
  <time datetime="{esc(site['tjstar_datetime'])}">{esc(site['tjstar_display'])}</time>
  <span class="countdown" data-tjstar-countdown="{esc(site['tjstar_datetime'])}" aria-hidden="true"></span>
  <a href="{esc(site['tjstar_url'])}">Astronomy presentations</a>
</div>"""


def project_card(project: dict, output_path: str, heading_level: int = 3) -> str:
    target = f"{project['year']}/{project['slug']}/index.html"
    artifact_labels = " · ".join(esc(item["label"]) for item in project["artifacts"])
    return f"""<article class="project-card">
  <p class="project-topic">{esc(project['topic'])}</p>
  <h{heading_level}><a href="{esc(href(output_path, target))}">{esc(project['title'])}</a></h{heading_level}>
  <p>{esc(project['summary'])}</p>
  <p class="project-availability">Available: {artifact_labels} · tjSTAR record</p>
</article>"""


def home_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    latest_year = site["latest_year"]
    year = year_definition(data, latest_year)
    projects = projects_for_year(data, latest_year)
    output = "index.html"
    feature_indexes = sorted({0, len(projects) // 2, len(projects) - 1}) if projects else []
    featured = "\n".join(project_card(projects[index], output) for index in feature_indexes)
    archive_link = href(output, f"{latest_year}/index.html")
    research_link = href(output, "research/index.html")
    content = f"""
<div class="home-shell">
  <div class="home-grid">
    <section class="home-intro" aria-labelledby="page-title">
      <p class="eyebrow">Thomas Jefferson High School for Science and Technology</p>
      <h1 id="page-title">{esc(site['full_name'])}</h1>
      <p class="lede">TJHSST's senior research laboratory for sustained work in astronomy, astrophysics, astronomical data analysis, instrumentation, and computational modeling.</p>
      <div class="quick-actions" aria-label="Featured actions">
        <a class="button primary" href="{esc(archive_link)}">Explore {esc(year['label'])} projects</a>
        <a class="button" href="{esc(href(output, 'about/index.html'))}">How the lab works</a>
      </div>
    </section>
    <aside class="research-rail" aria-labelledby="research-now-title">
      <p class="rail-label">Research archive</p>
      <h2 id="research-now-title">Latest work</h2>
      <a class="year-link" href="{esc(archive_link)}">
        <span>{esc(year['label'])}</span>
        <small>{len(projects)} {noun(len(projects), 'project record')}</small>
      </a>
      <a class="rail-link" href="{esc(research_link)}">Browse research by year</a>
      {countdown(site)}
    </aside>
  </div>

  <section class="home-section" aria-labelledby="featured-title">
    <div class="section-heading">
      <div>
        <p class="eyebrow">Research at a glance</p>
        <h2 id="featured-title">Questions across the astronomical sciences</h2>
      </div>
      <a class="text-link" href="{esc(archive_link)}">View all {len(projects)} projects</a>
    </div>
    <div class="project-grid">{featured}</div>
  </section>

  <section class="home-section compact-section" aria-labelledby="work-title">
    <div class="section-heading narrow-heading">
      <div>
        <p class="eyebrow">The work</p>
        <h2 id="work-title">A year built around evidence</h2>
      </div>
      <p>Students frame research questions, read technical literature, select defensible methods, analyze uncertainty, and communicate what their evidence supports.</p>
    </div>
  </section>
</div>"""
    return output, site["full_name"], "TJHSST's senior research laboratory for astronomy and astrophysics.", content


def research_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    output = "research/index.html"
    latest_slug = site["latest_year"]
    latest_year = year_definition(data, latest_slug)
    latest_projects = projects_for_year(data, latest_slug)
    latest_topics = list(dict.fromkeys(project["topic"].lower() for project in latest_projects))
    earlier_years = [year for year in reversed(data["years"]) if year["slug"] != latest_slug]
    archive_links = "\n".join(
        f'<a class="year-link compact-year-link" href="{esc(href(output, f"{year["slug"]}/index.html"))}"><span>{esc(year["label"])}</span><small>{len(projects_for_year(data, year["slug"]))} {noun(len(projects_for_year(data, year["slug"])), "project record")}</small></a>'
        for year in earlier_years
    )
    earlier_archives = f'<div class="year-list" aria-label="Earlier research years">{archive_links}</div>' if archive_links else ""
    content = f"""
<div class="page-shell">
  <header class="page-heading">
    <p class="eyebrow">Research</p>
    <h1>Browse the lab's work</h1>
    <p class="lede">Annual records collect concise accounts of the scientific question, method, and result, with retained papers and posters available as supporting artifacts.</p>
  </header>
  <div class="research-index-grid">
    <section class="year-feature" aria-labelledby="year-title">
      <p class="rail-label">Latest available year</p>
      <h2 id="year-title">{esc(latest_year['label'])} research</h2>
      <p>{len(latest_projects)} {noun(len(latest_projects), 'project')} spanning {esc(natural_list(latest_topics))}.</p>
      <a class="button primary" href="{esc(href(output, f'{latest_slug}/index.html'))}">Open the {esc(latest_year['label'])} archive</a>
{earlier_archives}
    </section>
    <aside class="research-rail research-index-rail" aria-label="Research events">
      {countdown(site)}
    </aside>
  </div>
</div>"""
    return output, "Research", "Browse annual research records from the TJHSST Astronomy & Astrophysics Research Lab.", content


def about_page(data: dict) -> tuple[str, str, str, str]:
    output = "about/index.html"
    content = f"""
<div class="page-shell article-shell">
  <header class="page-heading">
    <p class="eyebrow">About the lab</p>
    <h1>From learning astronomy to doing astronomy</h1>
    <p class="lede">The lab supports year-long senior research centered on precise questions, quantitative evidence, sustained iteration, and responsible scientific communication.</p>
  </header>
  <section class="content-section" aria-labelledby="practice-title">
    <h2 id="practice-title">Research practice</h2>
    <div class="practice-grid">
      <article><h3>Develop</h3><p>Read technical literature, identify a tractable question, and design a research plan with appropriate evidence.</p></article>
      <article><h3>Investigate</h3><p>Use observations, archives, computation, simulation, or instrumentation while recording choices and uncertainty.</p></article>
      <article><h3>Communicate</h3><p>Explain methods and conclusions through research writing, posters, talks, and critique from a scientific audience.</p></article>
    </div>
  </section>
  <section class="content-section split-section" aria-labelledby="modes-title">
    <div>
      <p class="eyebrow">Research modes</p>
      <h2 id="modes-title">Several paths to an astronomical question</h2>
    </div>
    <ul class="plain-list">
      <li>Observational astronomy and calibrated measurement</li>
      <li>Public survey catalogs, images, spectra, and time series</li>
      <li>Numerical models and computational astrophysics</li>
      <li>Instrumentation, automation, and data-quality methods</li>
    </ul>
  </section>
  <section class="content-section callout-section" aria-labelledby="records-title">
    <div>
      <p class="eyebrow">Public record</p>
      <h2 id="records-title">See what the work produced</h2>
    </div>
    <a class="button primary" href="{esc(href(output, 'research/index.html'))}">Browse research</a>
  </section>
</div>"""
    return output, "About the Lab", "How students conduct astronomy and astrophysics research at TJHSST.", content


def contact_page(data: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    output = "contact/index.html"
    email = esc(site["contact_email"])
    content = f"""
<div class="page-shell article-shell">
  <header class="page-heading">
    <p class="eyebrow">Contact</p>
    <h1>Connect with the lab</h1>
    <p class="lede">Questions about the research program, student work, or professional collaboration are welcome.</p>
  </header>
  <section class="contact-card" aria-labelledby="director-title">
    <p class="rail-label">Lab director</p>
    <h2 id="director-title">William Lynch</h2>
    <p>Thomas Jefferson High School for Science and Technology</p>
    <a class="button primary" href="mailto:{email}">Email the lab director</a>
  </section>
</div>"""
    return output, "Contact", "Contact the TJHSST Astronomy & Astrophysics Research Lab.", content


def artifact_link(item: dict, output_path: str) -> str:
    target = ROOT / item["path"]
    suffix = target.suffix.removeprefix(".").upper()
    size_mb = target.stat().st_size / (1024 * 1024)
    details = f"{suffix} · {size_mb:.1f} MB"
    return f'<a class="artifact-link" href="{esc(href(output_path, item["path"]))}"><span>{esc(item["label"])}</span><small>{esc(details)}</small></a>'


def year_page(data: dict, year: dict) -> tuple[str, str, str, str]:
    year_slug = year["slug"]
    projects = projects_for_year(data, year_slug)
    output = f"{year_slug}/index.html"
    cards = "\n".join(project_card(project, output, heading_level=2) for project in projects)
    content = f"""
<div class="page-shell">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="{esc(href(output, 'research/index.html'))}">Research</a><span aria-hidden="true">/</span><span>{esc(year['label'])}</span>
  </nav>
  <header class="page-heading archive-heading">
    <p class="eyebrow">Annual archive</p>
    <h1>{esc(year['label'])} projects</h1>
    <p class="lede">{len(projects)} concise {noun(len(projects), 'research record')}. Each page stands on its own as an account of the question, method, and result; retained papers, posters, and tjSTAR records provide the full artifacts.</p>
  </header>
  <div class="project-grid archive-grid">{cards}</div>
</div>"""
    return output, f"{year['label']} Projects", f"{len(projects)} {noun(len(projects), 'research project')} from the TJHSST Astronomy & Astrophysics Research Lab in {year['label']}.", content


def project_page(data: dict, project: dict) -> tuple[str, str, str, str]:
    site = data["site"]
    year_slug = project["year"]
    year = year_definition(data, year_slug)
    output = f"{year_slug}/{project['slug']}/index.html"
    artifact_links = "\n".join(artifact_link(item, output) for item in project["artifacts"])
    tjstar = f'<a class="artifact-link" href="{esc(project["tjstar_url"])}"><span>tjSTAR record</span><small>Filtered presentation entry</small></a>'
    collaboration = ""
    if project.get("collaboration"):
        collaboration = f"""<section class="record-section" aria-labelledby="collaboration-title">
  <p class="record-label">Collaboration</p>
  <h2 id="collaboration-title">Project-specific support</h2>
  <p>{esc(project['collaboration'])}</p>
</section>"""
    credits = ""
    if site.get("show_project_credits") and project.get("credits"):
        credits = f"""<details class="project-credits">
  <summary>Project credits</summary>
  <p>Student researchers: {esc(', '.join(project['credits']))}</p>
</details>"""
    content = f"""
<div class="page-shell record-shell">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="{esc(href(output, 'research/index.html'))}">Research</a><span aria-hidden="true">/</span><a href="{esc(href(output, f'{year_slug}/index.html'))}">{esc(year['label'])}</a><span aria-hidden="true">/</span><span>{esc(project['topic'])}</span>
  </nav>
  <div class="record-layout">
    <article class="record-main">
      <header class="record-heading">
        <p class="eyebrow">{esc(project['topic'])}</p>
        <h1>{esc(project['title'])}</h1>
        <p class="lede">{esc(project['summary'])}</p>
      </header>
      <section class="record-section" aria-labelledby="question-title">
        <p class="record-label">Research question</p>
        <h2 id="question-title">What did the project ask?</h2>
        <p>{esc(project['question'])}</p>
      </section>
      <section class="record-section" aria-labelledby="significance-title">
        <p class="record-label">Significance</p>
        <h2 id="significance-title">Why does it matter?</h2>
        <p>{esc(project['significance'])}</p>
      </section>
      <section class="record-section" aria-labelledby="method-title">
        <p class="record-label">Method</p>
        <h2 id="method-title">What did the team do?</h2>
        <p>{esc(project['method'])}</p>
      </section>
      <section class="record-section result-section" aria-labelledby="result-title">
        <p class="record-label">Principal result</p>
        <h2 id="result-title">What did the evidence show?</h2>
        <p>{esc(project['result'])}</p>
      </section>
{collaboration}
    </article>
    <aside class="artifact-panel" aria-labelledby="artifacts-title">
      <p class="rail-label">Full work</p>
      <h2 id="artifacts-title">Project artifacts</h2>
      <div class="artifact-list">{artifact_links}{tjstar}</div>
      <p class="artifact-note">The HTML record is a concise public account. Papers and posters retain the project's full presentation and authorship.</p>
      <a class="back-link" href="{esc(href(output, f'{year_slug}/index.html'))}">Back to all {esc(year['label'])} projects</a>
      {credits}
    </aside>
  </div>
</div>"""
    return output, project["title"], project["summary"], content


def render_all(data: dict) -> dict[str, str]:
    site = data["site"]
    specifications = [
        (*home_page(data), "home"),
        (*research_page(data), "research"),
        (*about_page(data), "about"),
        (*contact_page(data), "contact"),
    ]
    specifications.extend((*year_page(data, year), "research") for year in data["years"])
    specifications.extend((*project_page(data, project), "research") for project in data["projects"])
    rendered: dict[str, str] = {}
    for output_path, title, description, content, active in specifications:
        rendered[output_path] = layout(
            output_path=output_path,
            title=title,
            description=description,
            active=active,
            content=content,
            site=site,
        )
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated pages are missing or stale")
    args = parser.parse_args()
    rendered = render_all(load_data())
    stale: list[str] = []
    for relative, contents in rendered.items():
        destination = ROOT / relative
        if args.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != contents:
                stale.append(relative)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(contents, encoding="utf-8")
        print(f"generated {relative}")
    if stale:
        print("Generated pages are stale or missing:", file=sys.stderr)
        for relative in stale:
            print(f"  {relative}", file=sys.stderr)
        return 1
    if args.check:
        expected = set(rendered)
        for page in ROOT.rglob("*.html"):
            relative = page.relative_to(ROOT).as_posix()
            if "Generated by scripts/build_site.py" in page.read_text(encoding="utf-8") and relative not in expected:
                print(f"Orphan generated page: {relative}", file=sys.stderr)
                return 1
        print(f"All {len(rendered)} generated HTML pages are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
